# Generated by Django 5.2.1 on 2025-06-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('uiux', 'UI/UX Design'), ('frontend', 'Développement Web'), ('fullstack', 'Développement Full-Stack'), ('data', 'Analyse de Données'), ('perf', 'Optimisation de Performance')], default='défaut', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='portfolio/images/'),
        ),
    ]
