# Generated by Django 5.2.1 on 2025-06-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_project_link_project_category_project_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('uiux', 'UI/UX Design'), ('frontend', 'Développement Web'), ('fullstack', 'Développement Full-Stack'), ('data', 'Analyse de Données'), ('perf', 'Optimisation de Performance')], default='frontend', max_length=20),
        ),
    ]
